# Generated by Django 3.1.3 on 2020-11-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_costomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costomer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='costomer',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
