# Generated by Django 3.1.3 on 2020-11-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201115_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costomer',
        ),
    ]
