# Generated by Django 3.1.3 on 2020-11-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_costomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costomer',
            new_name='Customer',
        ),
    ]
